### PR TITLE
Convox Integration

### PR DESCRIPTION
**Pull request by nzoschke**
* Icons
* Description
* Configuration

I didn't yet fill out metrics.csv. Can I copy this from the ECS/Docker metrics somehow?

### CODE REVIEW

**Comment by irabinovitch** [comment]
@nzoschke In this case we'd leave out the csv until we add convox specific metrics in the future.

**Comment by nzoschke** [comment]
Makes sense. I'll have to read up more on how to best send custom metrics from a convox cluster to datadog.... Can our system use the running dd-agent somehow?

**Comment by dsahni** [comment]
Hi @nzoschke 👋 I realize its been a while this PR has been open, but just need one more thing before I can enable this integration tile -  do you have a Convox support email address, or another email address I can add as the maintainer of the integration?

**Comment by dsahni** [comment]
Hi @nzoschke, closing this PR as the tile has now been published. Thank you!

**Pull request closed without merging**
