### PR TITLE
Buddy Integration

### PR DESCRIPTION
**Pull request by mrszympek**

### CODE REVIEW

**Comment by dsahni** [comment]
@mrszympek Can you please replace the sample metrics in the metrics.csv file with the metrics your integration plans on sending?

**Comment by mrszympek** [comment]
@dsahni we don't send any metrics in our integration. Could you please remove the file? Other than that, everything should be set correctly.

**Comment by dsahni** [comment]
@mrszympek Our internal CI job requires the metrics.csv file be present, so in this case we can just leave the table empty.

Everything else looks good, all that is left is an email address for the maintainer of this tile. Is there a support email at Buddy, or would you like to provide your own? Let me know and I can update the [tile manifest](https://github.com/DataDog/integrations-extras/blob/master/buddy/manifest.json) accordingly.

**Comment by mrszympek** [comment]
@dsahni please use support@buddy.works. Thank you!

**Comment by dsahni** [comment]
✅Buddy integration is now public, closing PR

**Pull request closed without merging**
