### PR TITLE
Added Squadcast Integration tile details

### PR DESCRIPTION
**Pull request by raghuchinnannan**
- Added the details required for creating a Squadcast tile.
- This is a webhook based integration for alerts, so no metrics are being sent and the metadata.csv file is kept empty.

### CODE REVIEW

**Comment by dsahni** [comment]
Thanks for submitting this information @raghuchinnannan, we'll review and get back to you with any questions shortly!

**Comment by hithwen** [comment]
Hallo @raghuchinnannan!

About the included dashboard screenshot. That only makes sense if a screenboard json is included as well. Have a look at contrastsecurity as an example: https://github.com/DataDog/integrations-extras/tree/master/contrastsecurity/assets/dashboards

**Comment by raghuchinnannan** [comment]
Hi @hithwen 

The Dashboard screenshot is just to show how our dashboard would look like. We just use a webhook based integration to get data to our system. I'm not sure why the screenboard json is necessary and frankly we have no idea what that json is for.

I'm tagging @dsahni with whom we had a call regarding the integration and based on this we have created this PR.

Please let us know if we missed anything.

**Comment by hithwen** [comment]
Hi @raghuchinnannan, if you include the dashboard definition (the json file) in the PR we can make it available to any user of this integration. That is completely optional though so there is no need to include it. However including a screenshot without a definition file will be confusing to other users because a screenshot alone has little value.

**Comment by raghuchinnannan** [comment]
Hi @hithwen ,

I have removed the dashboard image from Readme. 

I hope now it can be merged without any confusion.

**Comment by dsahni** [comment]
Thanks @raghuchinnannan, I've created a `squadcast` branch in our [integrations-extras](https://github.com/DataDog/integrations-extras/tree/squadcast/squadcast) repository where I've made some more edits to the information you've submitted.

We can continue our conversation in the email thread on next steps to get the tile listed. Thank you!

**Comment by dsahni** [comment]
closing this PR

**Pull request closed without merging**
