### PR TITLE
Add images and description for the Opsmatic integration.

### PR DESCRIPTION
**Pull request by lisamoreno**

### CODE REVIEW

**Comment by mihasya** [comment]
Howdy @2bethere any chance to get this looked at soon?

**Comment by 2bethere** [comment]
@mihasya Thanks for pinging me. I just got back from vacation today. Let me reach out to our dev team and update you once I hear back. Thanks for being patient!

**Comment by 2bethere** [comment]
@mihasya  We have started the review process, can you please update metrics.csv and add in metrics you are planning on sending? This helps user search for data you are sending to us.

**Comment by lisamoreno** [comment]
Hey @2bethere -- thanks for getting back to us. We currently only send events to DataDog using your events API, http://docs.datadoghq.com/api/#events. In the future if we decide to send metrics, we will submit a new PR with the metrics.csv file completed. Let me know if you have any questions.

**Comment by truthbk** [comment]
@lisamoreno I just tested your integration tile and there's a couple of small problems with it, you should be able to fix in no time. 
1. Please set the background to white. It's currently a transparent background.
2. There's practically no padding to the top and bottom of your logos so our CSS is cutting into it. Could you guys leave more padding room around it? Probably about 15-20px would be a good idea. Canvas sizes are fine.

Thanks!

**Comment by lisamoreno** [comment]
@truthbk: Updated those images as you requested. Thank you!

**Comment by truthbk** [comment]
@lisamoreno the description: _Opsmatic provides real-time visibility of any change in the live state of computing infrastructure and intelligently alerts users before trouble begins_ is a bit too long and is getting trimmed. Would this be acceptable: _Opsmatic provides real-time visibility to changes in the live state of your infrastructure and intelligently alerts users before trouble begins_.?

**Comment by lisamoreno** [comment]
@truthbk: That'll work. Thank you!

**Pull request closed without merging**
