### PR TITLE
Documentation for Lightbend Reactive Platform integration.

### PR DESCRIPTION
**Pull request by henrikengstrom**

### CODE REVIEW

**Comment by zippolyte** [comment]
Hi @henrikengstrom,
I see you have listed 4 dashboards in the `manifest.json` but there can only be one default dashboard. Which one would you like us to keep ? 
Regards

**Comment by henrikengstrom** [comment]
@zippolight Please make the Akka actors dashboard the default one. Thanks.

**Comment by zippolyte** [comment]
Hey @henrikengstrom,
Sorry I just noticed but the dashboard you created is actually a TimeBoard and not a ScreenBoard, which is what we need. To create a Screenboard, you go to https://app.datadoghq.com/dash/list, select `New dashboard`, and click on `New ScreenBoard`(on the right). 
There you can make your changes and save your ScreenBoard. You can then send me the link of your ScreenBoard which should look like https://app.datadoghq.com/screen/0000/boardname.
Thanks

**Comment by henrikengstrom** [comment]
Hello @zippolyte. @marcweisman said we could start with the Timeboard dashboards since it is quite urgent to get this out. Is that still the case?

**Comment by marcweisman** [comment]
@henrikengstrom Yes, we're moving forward with the Timeboards. Sorry, I hadn't updated @zippolyte about that.

**Comment by henrikengstrom** [comment]
No worries @marcweisman

**Comment by henrikengstrom** [comment]
Hey @zippolyte. Any updates on this? Let me know if you need me to do something on my side?

**Comment by marcweisman** [comment]
Henrik,

Hippolyte just got this out to Prod. It's ready for use. I'd love to get a
blog post out to let people know  about it. I'll follow up via email.

**Comment by henrikengstrom** [comment]
Awesome news! Yes, let's follow up via email. Thanks guys.

**Comment by pvlugter** [comment]
@zippolyte: we have a single screenboard now, to replace the timeboards:

https://app.datadoghq.com/screen/170501/lightbend--akka-overview

**Comment by pvlugter** [comment]
lightbend-akka-overview

**Comment by zippolyte** [comment]
@pvlugter The timeboards have been replaced with your single screenboard

**Comment by pvlugter** [comment]
Thanks @zippolyte. Could we also have the integration docs updated with the latest changes in this PR?

**Comment by zippolyte** [comment]
@pvlugter Done

**Comment by pvlugter** [comment]
@zippolyte thanks!

**Pull request closed without merging**
