### PR TITLE
change the image size in the readme

### PR DESCRIPTION
**Pull request by deterralba**

### CODE REVIEW

**Comment by deterralba** [comment]
It would be nice to say "Your images must respect the [following guidelines](https://github.com/DataDog/devops/wiki/Integration-Graphics)", but the repo is private (hence is its wiki I think).
The guidelines should be public, we could write them in the public agent repo. What do you think?

**Comment by olivielpeau** [comment]
:+1: for the change

I agree that these guidelines should be made public. They should probably live in this repo/repo's wiki than in the agent's repo though, as integrations are not necessarily agent checks.

@irabinovitch What do you think?

**Comment by tmichelet** [comment]
+1 for the change, however these files must also be updated:
https://github.com/DataDog/IntegrationTemplate/tree/master/Integration/Images

About the guidelines, we'll update them later when this IntegrationTemplate repo will be deprecated, so I'd say let's leave the situation as is

**Comment by deterralba** [comment]
@tmichelet I've updated the template image. Merge?

**Comment by tmichelet** [comment]
:+1:

**Comment by irabinovitch** [comment]
@deterralba  Thanks for catching this.

**Pull request merged**
