### PR TITLE
Added Moxtra Integration

### PR DESCRIPTION
**Pull request by shahtanvi**
Will,
Moxtra integration details added. Let us know if you need anything else.

Thanks.

### CODE REVIEW

**Comment by truthbk** [comment]
Hi,

You put your files straight into the Integration/ directory. You weren't meant to do that, instead you should copy Integration/ to Moxtra/ and then change the files within Moxtra/. Please take a look at https://github.com/DataDog/IntegrationTemplate/blob/master/README.md for detailed instructions - you do have most of your work done, it's just in the wrong place.

Thanks! :)

**Comment by shahtanvi** [comment]
I see what you mean. Let me fix that.

**Comment by truthbk** [comment]
No worries, I can do this for you regardless - I'll do it manually. No need to put in a new PR. Let's just leave this one open for now until I merge your changes in.

**Comment by shahtanvi** [comment]
Okay perfect! Thank you so much.

**Pull request closed without merging**
