### PR TITLE
Initial version of the Ambassador / DataDog integration

### PR DESCRIPTION
**Pull request by richarddli**

### CODE REVIEW

**Comment by irabinovitch** [comment]
Thanks @richarddli . Our team is reviewing and will be in touch!

**Comment by richarddli** [comment]
Hi there, just wanted to ask on the status of this? Thanks!

**Comment by dsahni** [comment]
Hi @richarddli I've also  just emailed you as well - please include the envoy metrics in metadata.csv that the Ambassador integration will report and we can continue the process of testing this out.

Thank you for your PR!

**Comment by richarddli** [comment]
OK, I added metrics. Please let me know if you need anything else.

**Comment by dsahni** [comment]
Closing since this has already been merged to https://github.com/DataDog/integrations-extras

**Pull request closed without merging**
